// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oaxctvizaiftgsnzkdjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9heGN0dml6YWlmdGdzbnprZGpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4NDM5NjIsImV4cCI6MjA4NDQxOTk2Mn0.XS9qoqEEUKLmLvw5cZ542aCwCcqq07ev-zoiOOf1T8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});