// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avcqdbhnxzfkxxsqdvae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2Y3FkYmhueHpma3h4c3FkdmFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0Njg5MzgsImV4cCI6MjA4NTA0NDkzOH0.iU_Xrtj9hygo2XJDOkMbpDjTLkkqGmfcmMsH8F-bna4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});